# Authors
POST http://localhost:3000/api/authors
Content-Type: application/json

{
  "name": "Phablo",
  "birthDate": "2002-08-14",
  "sex": "M",
  "writingGenre": "Mystery"
}

###

GET http://localhost:3000/api/authors

###

####################################################

# Users
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Roberta Ferreira",
  "birthDate": "2007-05-15",
  "sex": "F",
  "address": "Rua da casa da Roberta, 123"
}

###
GET http://localhost:3000/api/users

###
################################################

# Books
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "A volta dos que não foram",
  "synopsis": "Se trata de um livro daqueles que nunca foram, mas que agora retornam para contar suas histórias.",
  "year": 2025,
  "author": "68ff6c11040d6d03f240fd41"
}

###
GET http://localhost:3000/api/books

##########################################################

# Loans
### Realizar Empréstimo (POST)
# Substitua <USER_ID> e <BOOK_ID> pelos IDs reais retornados pelas rotas de Users/Books
POST http://localhost:3000/api/loans
Content-Type: application/json

{
  "userId": "68ff6c39040d6d03f240fd43",
  "bookId": "68ff6c7b040d6d03f240fd47"
}

###

### Listar Empréstimos (GET)
GET http://localhost:3000/api/loans

###
