# Authors
POST http://localhost:3000/api/authors
Content-Type: application/json

{
  "name": "Teste",
  "birthDate": "2002-01-01",
  "sex": "M",
  "writingGenre": "Novel"
}

###

GET http://localhost:3000/api/authors

###

####################################################

# Users
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Matheus Meigre",
  "birthDate": "2001-11-24",
  "sex": "M",
  "address": "Rua das Flores, 456"
}

###
GET http://localhost:3000/api/users

###
################################################

# Books
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "Livro Teste",
  "synopsis": "Sinopse...",
  "year": 2024,
  "author": "<AUTHOR_ID>"
}

###
GET http://localhost:3000/api/books

##########################################################

# Loans
POST http://localhost:3000/api/loans
Content-Type: application/json

{
  "user": "Matheus Meigre",
  "book": "Livro Seed",
  "loanDate": "2025-10-27T12:34:56.789Z",
  "returnDate": "2025-10-30T12:34:56.789Z"
}

###

GET http://localhost:3000/api/loans

###
